export const LOGIN_SUCCESS = 'LOGIN SUCCESSS'
export const LOGIN_FAIL = 'LOGIN FAILED'
export const LOGOUT = 'LOG OUT'

//NOTIFY
export const NOTIFY_DELETE_SUCCESSFULLY = 'DELETE SUCESSFULLY'
export const CLOSE_NOTIFY = 'CLOSE NOTIFY'
export const FORCE_LOG_OUT = 'FORCE LOG OUT'
export const NOTIFY_ERROR = 'NOTIFY ERROR'
export const NOTIFY_UPDATE_SUCCESSFULLY = 'NOTIFY UPDATE SUCCESSFULLY'
export const NOTIFY_CREATE_CONTEST_SUCCESSFULLY = 'NOTIFY CREATE CONTEST SUCCESSFULLY'
export const NOTIFY_ACTIVE_CONTEST_SUCCESSFULLY = 'NOTIFY ACTIVE CONTEST SUCCESSFULLY'
export const NOTIFY_FINISH_CONTEST_SUCCESSFULLY = 'NOTIFY FINISH CONTEST SUCCESSFULLY'
export const NOTIFY_SUCCESSFULLY = 'NOTIFY SUCCESSFULLY'
export const SHOW_NOTI_FROM_SERVER = 'SHOW NOTI FROM SERVER'
export const UNSHOW_NOTI_FROM_SERVER = 'UNSHOW NOTI FROM SERVER'
export const CLOSE_BADGE = 'CLOSE_BADGE'


